title: "[Idea]: "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        ## 💡 Share an Idea
        Got an idea for improving ExpressionCache? Describe it here!
  - type: textarea
    id: idea
    attributes:
      label: The Idea
      description: What feature or improvement would you like to see?
      placeholder: "It would be helpful if..."
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Why this is useful
      description: Explain how this idea would improve the project or help others.
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: If you’ve thought of other approaches, list them here.
