name: PowerShell 5.1 Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run:
    uses: ./.github/workflows/reusable-pester.yml
    with:
      shell: powershell
