name: CI — Pester (PowerShell 7)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run:
    uses: ./.github/workflows/reusable-pester.yml
    with:
      shell: pwsh
